naoki-suzuki/driveRecordIOS

driveRecordIOS.xcodeproj/project.pbxproj
driveRecordIOS/FolderDetailViewContorller.swift

一人当たりの金額表示とLINE共有の処理
注）長坂君がレイアウトをしていると思うので、ボタンとコードを繋いでいません

FolderDetailの修正

---

driveRecordIOS/FolderDetail.storyboard
driveRecordIOS/FolderDetailViewContorller.swift

詳細画面＆共有機能作成

---

driveRecordIOS/FolderDetail.storyboard
driveRecordIOS/FolderDetailViewContorller.swift
driveRecordIOS/MoneyInsert.storyboard

詳細画面の明細削除機能の実装。
カメラ画面のフルスクリーン化の実装。

詳細画面削除機能・カメラ画面フルスクリーン化

---

driveRecordIOS/FolderDetail.storyboard
driveRecordIOS/MoneyInsert.storyboard

歯車アイコンのtitle変更

---

driveRecordIOS/MoneyInsert.storyboard
driveRecordIOS/MoneyInsertViewController.swift
driveRecordIOS/cameraViewController.swift

カメラ保存処理のコード変更
→保存するかどうかのアラート確認
　設定で写真の追加許可をしていない場合、エラーをアラートで表示
MoneyInsert画面のレイアウト修正
→写真保存画面のTopスペースの追加
　金額入力などのTextfieldの幅を変更

カメラの保存処理のコード変更

---

driveRecordIOS/FolderDetail.storyboard
driveRecordIOS/FolderDetailViewContorller.swift

共有ボタンをアイコンに変更しました。
ライン表示の空白の調整をしました。

共有ボタンの変更、Linetextの変更

---

driveRecordIOS.xcodeproj/project.pbxproj
driveRecordIOS/MoneyInsert.storyboard
driveRecordIOS/SavePhoto.storyboard

写真保存の画面をMoneyInsertに入れていたものを独立化

SavePhoto.storyboardの作成

---

driveRecordIOS/MoneyInsertViewController.swift
driveRecordIOS/folderCreateViewController.swift

FolderCreateとMoneyInsertのコメントの追加とインデントの修正
処理に変更は無し

コメントとインデントの修正

---

driveRecordIOS/FolderCreate.storyboard
driveRecordIOS/folderCreateViewController.swift

・メンバー入力時に、一番上から入力していない時に出るエラー処理で、重複して変数を書いていたので削除
・入力フォームで１０文字表示出来ていなかったので、表示できる様、幅を増大

FolderCreateのファイルを修正

---

driveRecordIOS/FolderDetail.storyboard
driveRecordIOS/FolderDetailViewContorller.swift

文字数ごとにレイアウト調整
・stackviewの条件別hiddenの実装
・nilエラーをif let構文による解消

詳細画面レイアウト変更

---

driveRecordIOS/FolderCreate.storyboard
driveRecordIOS/MoneyInsert.storyboard

PlaceFolderの設置

---

driveRecordIOS.xcodeproj/project.pbxproj
driveRecordIOS/Base.lproj/Main.storyboard
driveRecordIOS/FolderCreate.storyboard

画面のデザイン大きさ修正

---

driveRecordIOS.xcodeproj/project.pbxproj
driveRecordIOS/MoneyInsert.storyboard
driveRecordIOS/MoneyInsertViewController.swift
driveRecordIOS/SavePhoto.storyboard

MoneyInsertのデザイン修正
枠組みの作成や、ボタンのサイズ修正
SavePhotoのボタンのサイズ修正

MoneyInsertのデザイン修正

---

driveRecordIOS.xcodeproj/project.pbxproj
driveRecordIOS/MoneyInsertViewController.swift
driveRecordIOS/folderCreateViewController.swift

ドラムロール の箇所をタップする度に、現日時取得や一番上の値取得に変わってしまっていたのを修正

ドラムロールの値の取得修正

---

driveRecordIOS/FolderCreate.storyboard

フォルダ作成画面のデザイン修正

---

driveRecordIOS/MoneyInsert.storyboard

金額入力画面のデザイン修正
SEにてデザインのズレの修正および、警告修正

金額入力画面のデザイン修正

---

driveRecordIOS.xcodeproj/project.pbxproj
driveRecordIOS/ViewController.swift

ホーム画面の文言の改行修正

---

driveRecordIOS.xcodeproj/project.pbxproj
driveRecordIOS/Info.plist
driveRecordIOS/Support.storyboard

OSのダークモード対応
サポートボタンの戻るボタンの色の変更

OSのダークモード対応

---

driveRecordIOS/AppDelegate.swift
driveRecordIOS/MoneyInsertViewController.swift

金額入力画面の項目追加

---

driveRecordIOS/FolderCreate.storyboard
driveRecordIOS/MoneyInsert.storyboard

ボタンサイズと位置の変更
ボタンサイズを詳細画面と同じ大きさに変更
フォルダ作成画面のボタンの並べ方を横並びから縦並びに変更

ボタンサイズと位置の変更

---

driveRecordIOS/FolderCreate.storyboard

歯車ボタンのタイトル変更

---

driveRecordIOS/Convention ViewControlle.swift
driveRecordIOS/cameraViewController.swift

ナビゲーションの色変更

---

driveRecordIOS/FolderDetail.storyboard
driveRecordIOS/FolderDetailViewContorller.swift

iPadでLINE共有できるように対応

---

driveRecordIOS/FolderDetail.storyboard

ボタンサイズの固定化

---

driveRecordIOS/FolderCreate.storyboard
driveRecordIOS/MoneyInsert.storyboard
driveRecordIOS/MoneyInsertViewController.swift

・半角数字のテェック追加

---

driveRecordIOS/Support.storyboard
driveRecordIOS/SupportViewController.swift
driveRecordIOS/Version.storyboard
driveRecordIOS/VersionViewController.swift

サポート画面の情報の追加

---

driveRecordIOS/Version.storyboard

バージョンの仮情報入力

---

driveRecordIOS/folderCreateViewController.swift

メンバーの空欄チェックの実装

---

driveRecordIOS/FolderDetail.storyboard
driveRecordIOS/folderCreateViewController.swift

checkmemberメソッドの修正

---

driveRecordIOS/Base.lproj/Main.storyboard
driveRecordIOS/MoneyInsert.storyboard
driveRecordIOS/MoneyInsertViewController.swift
driveRecordIOS/cameraViewController.swift

カメラと地図の導線の削除

---

driveRecordIOS/Base.lproj/Main.storyboard
driveRecordIOS/Info.plist
driveRecordIOS/Map.storyboard
driveRecordIOS/MapViewController.swift

地図機能のアップデート

---

Podfile
Podfile.lock
driveRecordIOS/AppDelegate.swift
driveRecordIOS/DatabaseHelper.swift
driveRecordIOS/FolderCreate.storyboard
driveRecordIOS/FolderDetail.storyboard
driveRecordIOS/FolderDetailViewContorller.swift
driveRecordIOS/FolderinfoTable.swift
driveRecordIOS/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
driveRecordIOS/Settings.bundle/com.mono0926.LicensePlist.plist
driveRecordIOS/folderCreateViewController.swift

フェーズ2版機能実装

---

driveRecordIOS/FolderDetailViewContorller.swift

LINE共有チャット
